### PR TITLE
Browserify korean translation

### PR DESCRIPTION
**Pull request by MuhunKim**

### CODE REVIEW

**Comment by aroberge** [comment]
I was away for the past week and just came back.  I will try to review this as soon as possible and integrate it into my version.  (I do have a few work-related items to take care of first.)

Thank you for your contribution.

**Comment by MuhunKim** [comment]
Thanks!

**Comment by aroberge** [comment]
Thank you, I have uploaded the new version.  There is still some work for me to do before the translation can be all completed and available in all languages.

**Comment by aroberge** [comment]
Please note that the new version is a single html page multi-language version http://reeborg.ca/reeborg.html?lang=ko&mode=python  instead of having a different html file for each language (English, Korean, French, ....).

**Pull request merged**
