### PR TITLE
The better translation

### PR DESCRIPTION
**Pull request by MuhunKim**

### CODE REVIEW

**Comment by aroberge** [comment]
I _think_ the problem is that you are missing a double quote (") at the end of the line that starts with
`RUR.ko["PYTHON HELP"]`.  I can try to simply copy your changes into my branch directly.

**Comment by aroberge** [comment]
It might also be because I've made changes and you are trying to make changes at the same place (for "documentation").

**Comment by aroberge** [comment]
I have incorporated the changes in the latest commit.

**Comment by MuhunKim** [comment]
Thanks

**Pull request closed without merging**
