### PR TITLE
Additional translation

### PR DESCRIPTION
**Pull request by MuhunKim**
#### *Additional translation*

### CODE REVIEW

**Comment by aroberge** [comment]
Thank you!  I have almost finished incorporating all the text to ui_en.js, ui_ko.js, etc., so that everything relevant is available in all three languages.

**Comment by MuhunKim** [comment]
Congratulation :tada:!

**Comment by aroberge** [comment]
Thanks to you!   Note that there is one new string, on line 4 of ui_ko.js, that should be partly translated into Korean.

**Comment by MuhunKim** [comment]
@aroberge 
>Note that there is one new string, on line 4 of ui_ko.js, that should be partly translated into Korean.

#### line 4 of ui_ko.js
```js
RUR.ui_ko["ko-en"] = "{Korean translation here}<br>" +
"Mixed mode: User Interface in Korean; programming language in English.<br>";
```
to translate..
```js
RUR.ui_ko["ko-en"] = "{Korean translation here}<br>" +
"혼용된 모드: 사용자 환경은 한국어로 번역되어 있지만, 프로그래밍 언어는 영어로 이루어져 있습니다.<br>";
```

**Comment by aroberge** [comment]
고맙습니다!   You should be able to see the result at the bottom of the screen if you go to http://reeborg.ca/reeborg.html?lang=ko-en&mode=python

The existing tutorial uses English instructions (like `move()`) and it may be available for a long time.  For this reason, I want to make sure that the mixed mode (Korean/English) is always available.  However, at some point, Korean translations of robot commands might become available (like `앞으로가()` ?) and some new tutorials might be written.  At that point, I will add a "pure" Korean version.

Once again, thank you very much for your ongoing help in creating this Korean version.

**Comment by MuhunKim** [comment]
Imgur

Floor of the message was hidden :( 

I'm using 11 inch laptop..

>Korean translations of robot commands might become available (like 앞으로가() ?)

by the way, it's wrong translation ~~`앞으로가()`~~ -> `이동()`

Please use this translator or dictionary (Because Better than google service.)

* translator : http://better-translator.com
* dictionary : http://dic.daum.net/index.do?dic=eng

**Comment by aroberge** [comment]
Message hidden:  I should probably create a smaller default world (perhaps 10 by 10) to ensure that the message is shown.  I did not realize that this could be a problem; thank you for letting me know.

About the translation: I chose to translate "move forward" instead of "move" as I find "move" (which is used traditionally in all English versions of programs like Reeborg) to be not precise enough.  However, thank you for the suggestion for the better translator.

**Comment by aroberge** [comment]
The problem with the message being hidden should be fixed.

**Pull request merged**
